name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: nanda-kshr/instaroid:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Google Cloud Instance
      run: |
        gcloud compute ssh heavy-server \
          --project=${{ secrets.YOUR_GCP_PROJECT_ID }} \
          --zone=${{ secrets.YOUR_GCP_ZONE }} \
          --command='docker stop $(docker ps -q --filter ancestor=nanda-kshr/instaroid || echo "DUMMY") && docker rm $(docker ps -aq --filter ancestor=nanda-kshr/instaroid || echo "DUMMY") && docker rmi -f nanda-kshr/instaroid:latest || true && docker pull nanda-kshr/instaroid:latest && PORT=$((RANDOM % (5000 - 3000 + 1) + 3000)) && docker run -d -p $PORT:3000 --name instaroid-app nanda-kshr/instaroid:latest'
