
name: CI/CD to Google Cloud

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: heavy-server
  GCP_PROJECT_ID: <YOUR_GCP_PROJECT_ID> # <<< REMINDER: Replace with your GCP Project ID
  GCP_ZONE: <YOUR_GCP_ZONE>             # <<< REMINDER: Replace with your GCP Zone
  GCP_INSTANCE_NAME: heavy-server
  DOCKER_CONTAINER_NAME: heavy-server-container
  DOCKER_REMOTE_IMAGE: ${{ secrets.DOCKER_USERNAME }}/heavy-server:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.DOCKER_REMOTE_IMAGE }} .
        docker push ${{ env.DOCKER_REMOTE_IMAGE }}

    - name: Authenticate Google Cloud Service Account
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Google Cloud Instance
      run: |
        gcloud compute ssh ${{ env.GCP_INSTANCE_NAME }} \
          --project=${{ env.GCP_PROJECT_ID }} \
          --zone=${{ env.GCP_ZONE }} \
          --command="docker pull ${{ env.DOCKER_REMOTE_IMAGE }} && \
                     docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true && \
                     docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true && \
                     docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} -p 80:80 ${{ env.DOCKER_REMOTE_IMAGE }}"
