
name: CI/CD Pipeline for Instaroid

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/instaroid:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.YOUR_GCP_PROJECT_ID }}

      - name: Deploy to GCP Instance via SSH
        run: |
          gcloud compute ssh gcp@mahi \
            --zone=${{ secrets.YOUR_GCP_ZONE }} \
            --project=${{ secrets.YOUR_GCP_PROJECT_ID }} \
            --command="docker rmi -f ${{ secrets.DOCKER_USERNAME }}/instaroid:latest || true && \
                       docker pull ${{ secrets.DOCKER_USERNAME }}/instaroid:latest && \
                       docker stop instaroid-app || true && \
                       docker rm instaroid-app || true && \
                       docker run -d --name instaroid-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/instaroid:latest"
