
name: CI/CD to GCP Instance

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/instaroid:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to GCP Instance via SSH
      run: |
        gcloud compute ssh gcp@heavy-server \
          --project ${{ secrets.YOUR_GCP_PROJECT_ID }} \
          --zone ${{ secrets.YOUR_GCP_ZONE }} \
          --command "sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/instaroid:latest || true && \
                     sudo docker pull ${{ secrets.DOCKER_USERNAME }}/instaroid:latest && \
                     sudo docker stop instaroid-container || true && \
                     sudo docker rm instaroid-container || true && \
                     sudo docker run -d -p 3000:3000 --name instaroid-container -v /var/log/instaroid:/logs ${{ secrets.DOCKER_USERNAME }}/instaroid:latest"
