name: Deploy to GCP Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker build -t $DOCKER_USERNAME/instaroid:latest .
        docker push $DOCKER_USERNAME/instaroid:latest

    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.YOUR_GCP_PROJECT_ID }}

    - name: Deploy to GCP Instance
      env:
        GCP_PROJECT_ID: ${{ secrets.YOUR_GCP_PROJECT_ID }}
        GCP_ZONE: ${{ secrets.YOUR_GCP_ZONE }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        gcloud compute ssh gcp@heavy-server --project=$GCP_PROJECT_ID --zone=$GCP_ZONE --command="\
          sudo mkdir -p /var/log/instaroid && \
          sudo docker image rm $DOCKER_USERNAME/instaroid:latest --force || true && \
          sudo docker pull $DOCKER_USERNAME/instaroid:latest && \
          sudo docker stop instaroid-container || true && \
          sudo docker rm instaroid-container || true && \
          sudo docker run -d --name instaroid-container -p 3000:3000 -v /var/log/instaroid:/logs $DOCKER_USERNAME/instaroid:latest \
        "
