name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/instaroid:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/instaroid:latest

    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.YOUR_GCP_PROJECT_ID }}

    - name: Authenticate GCP Service Account
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Deploy to GCP instance via SSH
      run: |
        gcloud compute ssh heavy-server \
          --project=${{ secrets.YOUR_GCP_PROJECT_ID }} \
          --zone=${{ secrets.YOUR_GCP_ZONE }} \
          --command="sudo docker stop instaroid-container || true && sudo docker rm instaroid-container || true && sudo docker pull ${{ secrets.DOCKER_USERNAME }}/instaroid:latest && sudo docker run -d --name instaroid-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/instaroid:latest"
